# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180413_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_display',
            field=models.BooleanField(default=True, verbose_name='首页显示'),
        ),
        migrations.AddField(
            model_name='category',
            name='nav_display',
            field=models.BooleanField(default=True, verbose_name='导航显示'),
        ),
    ]
