# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180413_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='nav_display',
        ),
        migrations.AlterField(
            model_name='category',
            name='home_display',
            field=models.BooleanField(default=True, verbose_name='导航显示'),
        ),
    ]
